DATA CLAIMS_DATA_GROUP1_MED;
SET CLAIMS_DATA_GROUP1_MED;
FORMAT SVC_CAT2 $200.;
IF MR_LINE_DESC1="FIP" AND UPCASE(SVC_CAT) IN ("ALCOHOL AND DRUG ABUSE-HOSPITAL" , "ALCOHOL AND DRUG ABUSE-RESIDENTIAL")
                        THEN SVC_CAT2 = "Alcohol and Drug Abuse";
ELSE IF MR_LINE_DESC1="FIP" AND UPCASE(SVC_CAT) IN ("MAT NORM DELIVERY" , "MAT NORM DELIVERY-MOM\BABY CMBND")
                        THEN SVC_CAT2="Mat Norm Delivery";
ELSE IF MR_LINE_DESC1="FIP" AND UPCASE(SVC_CAT) IN ("MAT CSECT DELIVERY" , "MAT CSECT DELIVERY-MOM\BABY CMBND")
                        THEN SVC_CAT2="Mat Csect Delivery";
ELSE IF MR_LINE_DESC1="FIP" AND UPCASE(SVC_CAT) IN ("PSYCHIATRIC-HOSPITAL" , "PSYCHIATRIC-RESIDENTIAL")
                        THEN SVC_CAT2="Psychiatric";
ELSE IF MR_LINE_DESC1="FIP" AND UPCASE(SVC_CAT) IN ("WELL NEWBORN-CSECT DELIVERY" , "WELL NEWBORN-UNKNOWN DELIVERY")
                        THEN SVC_CAT2="Well Newborn";

ELSE IF MR_LINE_DESC1="FOP" AND UPCASE(SVC_CAT) IN ("RADIOLOGY GENERAL-DIAGNOSTIC" , "RADIOLOGY GENERAL-THERAPEUTIC")
                        THEN SVC_CAT2="Radiology General";
ELSE IF MR_LINE_DESC1="FOP" AND UPCASE(SVC_CAT) IN ("RADIOLOGY - CT/MRI/PET-CT SCAN" , "RADIOLOGY - CT/MRI/PET-MRI" , "RADIOLOGY - CT/MRI/PET-PET")
                        THEN SVC_CAT2="Radiology - CT/MRI/PET";
ELSE IF MR_LINE_DESC1="FOP" AND UPCASE(SVC_CAT) IN ("ALCOHOL & DRUG ABUSE-INTENSIVE OUTPATIENT" , "ALCOHOL & DRUG ABUSE-PARTIAL HOSPITALIZATION")
                        THEN SVC_CAT2="Alcohol & Drug Abuse";
ELSE IF MR_LINE_DESC1="FOP" AND UPCASE(SVC_CAT) IN ("PSYCHIATRIC-INTENSIVE OUTPATIENT" , "PSYCHIATRIC-PARTIAL HOSPITALIZATION")
                        THEN SVC_CAT2="Psychiatric";
ELSE IF MR_LINE_DESC1="FOP" AND UPCASE(SVC_CAT) IN ("PREVENTIVE-COLONOSCOPY" , "PREVENTIVE-GENERAL" , "PREVENTIVE-LAB" , "PREVENTIVE-MAMMOGRAPHY")
                        THEN SVC_CAT2="Preventive";
ELSE IF MR_LINE_DESC1="FOP" AND UPCASE(SVC_CAT) IN ("OTHER-BLOOD" , "OTHER-CLINIC" , "OTHER-DME/SUPPLIES" , "OTHER-DIAGNOSTIC" , "OTHER-DIALYSIS" , "OTHER-GENERAL" , "OTHER-PULMONARY" , "OTHER-TRTMT/SPCLTYSVCS")
                        THEN SVC_CAT2="Other";

ELSE IF MR_LINE_DESC1="PROF" AND UPCASE(SVC_CAT) IN ("INPATIENT VISITS-ALCOHOL AND DRUG ABUSE" , "INPATIENT VISITS-MEDICAL" , "INPATIENT VISITS-PSYCHIATRIC")
                         THEN SVC_CAT2="Inpatient Visits";
ELSE IF MR_LINE_DESC1="PROF" AND UPCASE(SVC_CAT) IN ("MATERNITY-ANCILLARY" , "MATERNITY-ANESTHESIA" , "MATERNITY-CESAREAN DELIVERIES" , "MATERNITY-NON-DELIVERIES" , "MATERNITY-NORMAL DELIVERIES")
                         THEN SVC_CAT2="Maternity";
ELSE IF MR_LINE_DESC1="PROF" AND UPCASE(SVC_CAT) IN ("OFFICE/HOME VISITS-PCP" , "OFFICE/HOME VISITS-SPECIALIST")
                         THEN SVC_CAT2="Office/Home Visits";
ELSE IF MR_LINE_DESC1="PROF" AND UPCASE(SVC_CAT) IN ("ER VISITS AND OBSERVATION CARE-ER VISITS" , "ER VISITS AND OBSERVATION CARE-OBSERVATION CARE")
                         THEN SVC_CAT2="ER Visits and Observation Care";
ELSE IF MR_LINE_DESC1="PROF" AND UPCASE(SVC_CAT) IN ("PREVENTIVE OTHER-COLONOSCOPY" , "PREVENTIVE OTHER-GENERAL" , "PREVENTIVE OTHER-LAB" , "PREVENTIVE OTHER-MAMMOGRAPHY")
                         THEN SVC_CAT2="Preventive Other";
ELSE IF MR_LINE_DESC1="PROF" AND UPCASE(SVC_CAT) IN ("RADIOLOGY IP-CT SCAN" , "RADIOLOGY IP-MRI" , "RADIOLOGY IP-PET")
                         THEN SVC_CAT2="Radiology IP";
ELSE IF MR_LINE_DESC1="PROF" AND UPCASE(SVC_CAT) IN ("RADIOLOGY IP - GENERAL-DIAGNOSTIC" , "RADIOLOGY IP - GENERAL-THERAPEUTIC")
                         THEN SVC_CAT2="Radiology IP - General";
ELSE IF MR_LINE_DESC1="PROF" AND UPCASE(SVC_CAT) IN ("RADIOLOGY OFFICE - CT/MRI/PET-CT SCAN" , "RADIOLOGY OFFICE - CT/MRI/PET-CT SCAN - RADIOLOGY CENTER" , "RADIOLOGY OFFICE - CT/MRI/PET-MRI" , "RADIOLOGY OFFICE - CT/MRI/PET-MRI - RADIOLOGY CENTER" , "RADIOLOGY OFFICE - CT/MRI/PET-PET" , "RADIOLOGY OFFICE - CT/MRI/PET-PET - RADIOLOGY CENTER")
                         THEN SVC_CAT2="Radiology Office - CT/MRI/PET";
ELSE IF MR_LINE_DESC1="PROF" AND UPCASE(SVC_CAT) IN ("RADIOLOGY OFFICE - GENERAL-DIAGNOSTIC" , "RADIOLOGY OFFICE - GENERAL-RADIOLOGY CENTER - DIAGNOSTIC" , "RADIOLOGY OFFICE - GENERAL-RADIOLOGY CENTER - THERAPEUTIC" , "RADIOLOGY OFFICE - GENERAL-THERAPEUTIC")
                         THEN SVC_CAT2="Radiology Office - General";


ELSE IF MR_LINE_DESC1="PROF" AND UPCASE(SVC_CAT) IN ("RADIOLOGY OP - GENERAL-DIAGNOSTIC" , "RADIOLOGY OP - GENERAL-THERAPEUTIC")
                         THEN SVC_CAT2="Radiology OP - General";
ELSE IF MR_LINE_DESC1="PROF" AND UPCASE(SVC_CAT) IN ("RADIOLOGY OP- CT/MRI/PET-CT SCAN" , "RADIOLOGY OP- CT/MRI/PET-MRI" , "RADIOLOGY OP- CT/MRI/PET-PET")
                         THEN SVC_CAT2="Radiology OP- CT/MRI/PET";
ELSE IF MR_LINE_DESC1="PROF" AND UPCASE(SVC_CAT) IN ("PATHOLOGY/LAB - INPATIENT & OUTPATIENT-INPATIENT" , "PATHOLOGY/LAB - INPATIENT & OUTPATIENT-OUTPATIENT")
                         THEN SVC_CAT2="Pathology/Lab - Inpatient & Outpatient";
ELSE IF MR_LINE_DESC1="PROF" AND UPCASE(SVC_CAT) IN ("PATHOLOGY/LAB - OFFICE-GENERAL" , "PATHOLOGY/LAB - OFFICE-INDEPENDENT LAB" , "PATHOLOGY/LAB - OFFICE-VENIPUNCTURE")
                         THEN SVC_CAT2="Pathology/Lab - Office";
ELSE IF MR_LINE_DESC1="PROF" AND UPCASE(SVC_CAT) IN ("MISCELLANEOUS MEDICAL-CENTRAL NERVOUS SYSTEM TESTS" , "MISCELLANEOUS MEDICAL-DERMATOLOGY" , "MISCELLANEOUS MEDICAL-DIALYSIS" , "MISCELLANEOUS MEDICAL-GASTROENTEROLOGY" , "MISCELLANEOUS MEDICAL-GENERAL" , "MISCELLANEOUS MEDICAL-NEUROLOGY" , "MISCELLANEOUS MEDICAL-NON-INVAS. VASC. DIAG. STUDIES" , "MISCELLANEOUS MEDICAL-OPHTHALMOLOGY"
                         , "MISCELLANEOUS MEDICAL-OTORHINOLARYNGOLOGY" , "MISCELLANEOUS MEDICAL-PULMONOLOGY" , "MISCELLANEOUS MEDICAL-VESTIBULAR FUNCTION TESTS")
                         THEN SVC_CAT2="Miscellaneous Medical";
ELSE IF MR_LINE_DESC1="OTH" AND UPCASE(SVC_CAT) IN ("HOME HEALTH CARE-HH" , "HOME HEALTH CARE-HOSPICE")
                         THEN SVC_CAT2="Home Health Care";
ELSE IF MR_LINE_DESC1="ADDL" AND UPCASE(SVC_CAT) IN ("BENEFITS OTHER-ACUPUNCTURE" , "BENEFITS OTHER-DENTAL" , "BENEFITS OTHER-DOCUMENTATION/UNCLASSIFIED" , "BENEFITS OTHER-GENERAL" , "BENEFITS OTHER-HEARING AIDS" , "BENEFITS OTHER-NON-EMERGENCY TRANSPORTATION" , "BENEFITS OTHER-REPRODUCTIVE MEDICINE" , "BENEFITS OTHER-TEMPORARY CODES")
                         THEN SVC_CAT2="Benefits Other";

/*ELSE IF MR_LINE_DESC1="OTH" AND UPCASE(SVC_CAT) IN ("PRESCRIPTION DRUGS-NON-SPECIALTY GENERIC" , "PRESCRIPTION DRUGS-NON-SPECIALTY MULTI SOURCE BRAND" , "PRESCRIPTION DRUGS-NON-SPECIALTY SINGLE SOURCE BRAND" , "PRESCRIPTION DRUGS-OTC" , "PRESCRIPTION DRUGS-SPECIALTY") */
/*                         THEN SVC_CAT2="Prescription Drugs";*/

ELSE SVC_CAT2 = SVC_CAT;

RUN;


DATA CLAIMS_DATA_GROUP1_MED;
SET CLAIMS_DATA_GROUP1_MED;
IF MR_LINE_DESC1 ="OTH" AND	UPCASE(SVC_CAT2)="HOME HEALTH CARE" then MR_LINE_DESC1_FINAL = "PROF";
ELSE IF MR_LINE_DESC1 ="OTH" AND	UPCASE(SVC_CAT2)="AMBULANCE" then MR_LINE_DESC1_FINAL = "PROF";
ELSE IF MR_LINE_DESC1 ="OTH" AND	UPCASE(SVC_CAT2)="DME AND SUPPLIES" then MR_LINE_DESC1_FINAL = "PROF";
ELSE IF MR_LINE_DESC1 ="OTH" AND	UPCASE(SVC_CAT2)="PROSTHETICS" then MR_LINE_DESC1_FINAL = "PROF";
/*ELSE IF MR_LINE_DESC1 ="OTH" AND	UPCASE(SVC_CAT2)="PRESCRIPTION DRUGS" then MR_LINE_DESC1_FINAL = "PROF";*/

ELSE IF MR_LINE_DESC1 ="ADDL" AND UPCASE(SVC_CAT2) ="BENEFITS OTHER" then MR_LINE_DESC1_FINAL = "PROF";
ELSE IF MR_LINE_DESC1 ="ADDL" AND UPCASE(SVC_CAT2) ="BENEFITS GLASSES/CONTACTS" then MR_LINE_DESC1_FINAL = "PROF";
ELSE MR_LINE_DESC1_FINAL=MR_LINE_DESC1;
RUN;

proc sql;
create table Summary_Group1 as
select distinct MR_LINE_DESC1_FINAL, SVC_CAT2,count (distinct CLAIMID) as Total_Claim_Count,
sum(PAID) as Total_Paid_Amount
from CLAIMS_DATA_GROUP1_MED
group by MR_LINE_DESC1, SVC_CAT2;
quit;
